# Generated by Django 3.1.7 on 2021-05-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_auto_20210507_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='password',
            new_name='passw',
        ),
    ]
