# Generated by Django 3.1.7 on 2021-05-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0003_auto_20210507_2002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='login',
        ),
    ]
