# Generated by Django 3.1.7 on 2021-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0004_auto_20210507_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='passw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='post',
            table='login2',
        ),
    ]
